package basicTest;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class LoginTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		
		
		
		
		//driver - 
		System.setProperty("webdriver.chrome.driver", ".\\drivers\\chromedriver.exe");
		
		
		
		//launch chrome browser
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		//driver.quit();
	}

	@Test
	public void verifyLoginTest() {
		driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".orangehrm-login-forgot-header"));
			assert (elements.size() > 0);
		}
		driver.findElement(By.name("username")).sendKeys("Admin");
		assertThat(driver.findElement(By.cssSelector(".orangehrm-login-forgot-header")).getText(),
				is("Forgot your password?"));
		driver.findElement(By.name("password")).sendKeys("admin123");
		driver.findElement(By.cssSelector(".oxd-button")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".oxd-text--h6"));
			assert (elements.size() > 0);
		}
		assertThat(driver.findElement(By.cssSelector(".oxd-text--h6")).getText(), is("PIM"));
		driver.findElement(By.cssSelector(".oxd-userdropdown-name")).click();
		driver.findElement(By.linkText("Logout")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".orangehrm-login-forgot-header"));
			assert (elements.size() > 0);
		}
		assertThat(driver.findElement(By.cssSelector(".orangehrm-login-forgot-header")).getText(),
				is("Forgot your password?"));
	}
}
